server:
  port: 9020
spring:
  application:
    name:   Organization-server
  datasource:
    username: root
    password: Cloud@123$
    url: jdbc:mysql://localhost:3306/fisglobal
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  